# Generated by Django 6.0.6 on 2026-06-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Numéro')),
                ('room_type', models.CharField(choices=[('single', 'Chambre Simple'), ('double', 'Chambre Double'), ('suite', 'Suite'), ('family', 'Chambre Familiale'), ('deluxe', 'Chambre Deluxe')], max_length=20, verbose_name='Type')),
                ('floor', models.PositiveIntegerField(verbose_name='Étage')),
                ('capacity', models.PositiveIntegerField(default=2, verbose_name='Capacité')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix/nuit')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('occupied', 'Occupée'), ('maintenance', 'En maintenance'), ('cleaning', 'En nettoyage')], default='available', max_length=20)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('has_wifi', models.BooleanField(default=True, verbose_name='WiFi')),
                ('has_ac', models.BooleanField(default=True, verbose_name='Climatisation')),
                ('has_tv', models.BooleanField(default=True, verbose_name='TV')),
                ('has_minibar', models.BooleanField(default=False, verbose_name='Minibar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chambre',
                'verbose_name_plural': 'Chambres',
                'ordering': ['number'],
            },
        ),
    ]
