# Generated by Django 6.0.6 on 2026-06-15 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0001_initial'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(verbose_name='Date arrivée')),
                ('check_out_date', models.DateField(verbose_name='Date départ')),
                ('actual_check_in', models.DateTimeField(blank=True, null=True, verbose_name='Arrivée réelle')),
                ('actual_check_out', models.DateTimeField(blank=True, null=True, verbose_name='Départ réel')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('checked_in', 'Enregistrée'), ('checked_out', 'Terminée'), ('cancelled', 'Annulée'), ('no_show', 'Non présenté')], default='pending', max_length=20)),
                ('adults', models.PositiveIntegerField(default=1, verbose_name='Adultes')),
                ('children', models.PositiveIntegerField(default=0, verbose_name='Enfants')),
                ('special_requests', models.TextField(blank=True, verbose_name='Demandes spéciales')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix/nuit')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reservations', to=settings.AUTH_USER_MODEL)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='guests.guest', verbose_name='Client')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='rooms.room', verbose_name='Chambre')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-created_at'],
            },
        ),
    ]
